refactor for hugo 0.147.0

diff --git a/clogrc/clog.config.yaml b/clogrc/clog.config.yaml
--- a/clogrc/clog.config.yaml
+++ b/clogrc/clog.config.yaml
@@ -12,7 +12,7 @@
 #                  |_|    |_|
 # -----------------------------------------------------------------------------
 snippets:
-  build: |
+  kobuild: |
     [ -d content ] && rm content
     eval "$(clog project config)"
     clog Check pre-build
@@ -31,32 +31,46 @@ snippets:
     dockerfile="clogrc/dockerfile"
     platform="linux/amd64"
     clog Log -I "$(((step+=1))). building docker image with$cT $dockerfile "
-
+  watch: |
+    [ ! -d content ] && ln -s documentation/content content
+    hugo server --port=1313 --logLevel debug --buildDrafts --buildFuture --buildExpired --cleanDestinationDir
+    rm content
   is-prod-release: |
     [ "prod" == "$(yq -r '.[0].build'  assets/data/releases.yaml)" ]
   git:
     tag:
       # pihuw, like Hugo & golang requires a "v"
       ref: echo "v$(yq -r '.[0].version'  assets/data/releases.yaml)"
+      # a go package needs a preceding "v"
+      refgo: echo "v$(clog git tag ref)"
     message:
       ref:  yq -r '.[0].note'  assets/data/releases.yaml
+    suffix: |
+      b="$(git branch --show-current)"
+      [[ "$b" == main ]] && echo "" || echo "$b"|tr -d '[:blank:]'"
   project:
     config: |
       PROJECT=pihuw
       DOCKER_NS=mrmxf
     has:
-      fomantic: cat layouts/partials/tmpl/head-cdn|grep -oE '[0-9]+\.[0-9]+\.[0-9]+'|tail -1
+      fomantic: cat layouts/_partials/tmpl/head-cdn|grep -oE '[0-9]+\.[0-9]+\.[0-9]+'|tail -1
       hugo: hugo version|grep -oE '[0-9]\.[0-9]+\.[0-9]+'
       git-lfs: git-lfs version|grep -oE '[0-9]\.[0-9]+\.[0-9]+'|head -1
     needs:
+      # grab the golang version from go.mod
+      golang: cat go.mod|grep '^go '|grep -oE '[0-9]\.[0-9]+\.[0-9]+'
+      # hunt for the hugo version
       hugo: |
-        j="$(curl -sL https://api.github.com/repos/gohugoio/hugo/releases/latest)"
-        echo "$(   echo $j | jq -r '.name   | ltrimstr("v")')"
+        # grab the version from configuration
+        if [ -f hugo .yaml ];then
+          yq -r '.module.hugoVersion.min' hugo.yaml
+        elif [ -f config/_default/module.yaml ];then
+          yq -r '.hugoVersion.min' config/_default/module.yaml
+        else
+          echo "hugo config not found"
+        fi
       git-lfs: echo "3.6.0"
-  watch: |
-    [ ! -d content ] && ln -s documentation/content content
-    hugo server --port=1313 --logLevel debug --buildDrafts --buildFuture --buildExpired --cleanDestinationDir
-    rm content
+
 # =============================================================================
 #    ___   _                 _
 #   / __| | |_    ___   __  | |__
